const movieIcon =
    'https://images.unsplash.com/photo-1690475780983-281a1031dd43?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80';

const mokupFilms = [
    {
        id: 1,
        title: 'Movie1',
        cover: movieIcon,
        duration: '1ч22м',
        isSaved: true,
    },
    {
        id: 2,
        title: 'Movie2',
        cover: movieIcon,
        duration: '1ч22м',
        isSaved: false,
    },
    {
        id: 3,
        title: 'Movie3',
        cover: movieIcon,
        duration: '1ч22м',
        isSaved: true,
    },
    {
        id: 4,
        title: 'Movie4',
        cover: movieIcon,
        duration: '1ч22м',
        isSaved: true,
    },
    {
        id: 5,
        title: 'Movie5',
        cover: movieIcon,
        duration: '1ч22м',
        isSaved: false,
    },
    {
        id: 6,
        title: 'Movie6',
        cover: movieIcon,
        duration: '1ч22м',
        isSaved: true,
    },
    {
        id: 7,
        title: 'Movie7',
        cover: movieIcon,
        duration: '1ч22м',
        isSaved: true,
    },
    {
        id: 8,
        title: 'Movie8',
        cover: movieIcon,
        duration: '1ч22м',
        isSaved: false,
    },
    {
        id: 9,
        title: 'Movie9',
        cover: movieIcon,
        duration: '1ч22м',
        isSaved: true,
    },
    {
        id: 10,
        title: 'Movie10',
        cover: movieIcon,
        duration: '1ч22м',
        isSaved: false,
    },
    {
        id: 11,
        title: 'Movie11',
        cover: movieIcon,
        duration: '1ч22м',
        isSaved: false,
    },
    {
        id: 12,
        title: 'Movie11',
        cover: movieIcon,
        duration: '1ч22м',
        isSaved: false,
    },
    {
        id: 13,
        title: 'Movie11',
        cover: movieIcon,
        duration: '1ч22м',
        isSaved: false,
    },
    {
        id: 14,
        title: 'Movie11',
        cover: movieIcon,
        duration: '1ч22м',
        isSaved: false,
    },
    {
        id: 15,
        title: 'Movie11',
        cover: movieIcon,
        duration: '1ч22м',
        isSaved: false,
    },
    {
        id: 16,
        title: 'Movie11',
        cover: movieIcon,
        duration: '1ч22м',
        isSaved: false,
    },
    {
        id: 17,
        title: 'Movie11',
        cover: movieIcon,
        duration: '1ч22м',
        isSaved: false,
    },
    {
        id: 18,
        title: 'Movie11',
        cover: movieIcon,
        duration: '1ч22м',
        isSaved: false,
    },
    {
        id: 19,
        title: 'Movie11',
        cover: movieIcon,
        duration: '1ч22м',
        isSaved: false,
    },
    {
        id: 20,
        title: 'Movie11',
        cover: movieIcon,
        duration: '1ч22м',
        isSaved: false,
    },
    {
        id: 21,
        title: 'Movie11',
        cover: movieIcon,
        duration: '1ч22м',
        isSaved: false,
    },
    {
        id: 22,
        title: 'Movie11',
        cover: movieIcon,
        duration: '1ч22м',
        isSaved: false,
    },
    {
        id: 23,
        title: 'Movie11',
        cover: movieIcon,
        duration: '1ч22м',
        isSaved: false,
    },
    {
        id: 24,
        title: 'Movie11',
        cover: movieIcon,
        duration: '1ч22м',
        isSaved: true,
    },

    {
        id: 25,
        title: 'Movie11',
        cover: movieIcon,
        duration: '1ч22м',
        isSaved: false,
    },
];

export default mokupFilms;
